name: Deploy MarketPlace

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ["ubuntu-latest"]

    steps:
      - name: Checkout code
        uses: action/checkout@v4
      - name: Set up Node.js
        uses: action/setup-node@v4
        with:
          node-version: "22.17"
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Upload production build
        uses: action/upload-artifact@v4
        with:
          name: react-build
          path: build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./build
